version: "3.9"
networks:
  ates:
    driver: bridge
volumes:
  v-auth-db:
    driver: local
  v-tasks-db:
    driver: local
services:
  auth-db:
    image: postgres
    volumes:
      - v-auth-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - ates

  auth-webpack:
    build: ./auth
    command: ./bin/webpack-dev-server --inline true
    ports:
      - "4011:3035"
    volumes:
      - ./auth:/myapp
    networks:
      - ates

  auth:
    build: ./auth
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      AUTH_SECRET_KEY: "-----BEGIN RSA PRIVATE KEY-----\nMIIBOgIBAAJBAMPeL5veiZKnZEXm7X6tiTd0j66th4muxD/+gJjju2ePTEfkoHir\ndy30KFakNn03wZ8jIY2ETS/6Qi6WKGzNCQ8CAwEAAQJATI34D7UAEljooUWsB7ou\nCoW9bumWMyMiw1xmyNshsUyps8MUZFDHX/qrTEvmFJUo8+ZGPwrl+lk0+yWOkBku\nQQIhAPsV5V241Y/vuokxglsXmTQYGTrH7lWU24JyU7Y7JbwhAiEAx7OdBErAoPyV\nRnKGYmSeFnd3LQwnLANEaeHVCHgnny8CIBvw4tZcJD/hQJPV05jJdn4KlHwrFYWm\njArnKBOmX1uhAiBmz6WqrAF34BHJ7vQYe8yXrHGCk5snIZd7G3Tdo15iqQIhAMgR\nNZ6+zccjrxYoLJM+YyMBBAMaflbk2AEtL+BVg0UX\n-----END RSA PRIVATE KEY-----\n"
      MESSAGE_BROKER: "broker:9092"
    ports:
      - "4010:3000"
    volumes:
      - ./auth:/myapp
    links:
      - auth-db
      - broker
    depends_on:
      - auth-db
      - auth-webpack
      - broker
    networks:
      - ates


  tasks-db:
    image: postgres
    volumes:
      - v-tasks-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - ates

  tasks-webpack:
    build: ./tasks
    command: ./bin/webpack-dev-server --inline true
    ports:
      - "4021:3035"
    volumes:
      - ./tasks:/myapp
    networks:
      - ates

  tasks:
    build: ./tasks
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      AUTH_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----\nMFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMPeL5veiZKnZEXm7X6tiTd0j66th4mu\nxD/+gJjju2ePTEfkoHirdy30KFakNn03wZ8jIY2ETS/6Qi6WKGzNCQ8CAwEAAQ==\n-----END PUBLIC KEY-----\n"
      AUTH_URL: "http://localhost:4010/token"
      MESSAGE_BROKER: "broker:9092"
      BUNDLE_GEMFILE: "/myapp/Gemfile"
    ports:
      - "4020:3000"
    volumes:
      - ./tasks:/myapp
    depends_on:
      - tasks-db
      - tasks-webpack
      - broker
    networks:
      - ates

  tasks-karafka:
    build: ./tasks
    command: bash -c "bundle exec karafka server"
    environment:
      AUTH_PUBLIC_KEY: "-----BEGIN PUBLIC KEY-----\nMFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAMPeL5veiZKnZEXm7X6tiTd0j66th4mu\nxD/+gJjju2ePTEfkoHirdy30KFakNn03wZ8jIY2ETS/6Qi6WKGzNCQ8CAwEAAQ==\n-----END PUBLIC KEY-----\n"
      AUTH_URL: "http://localhost:4010/token"
      MESSAGE_BROKER: "broker:9092"
      BUNDLE_GEMFILE: "/myapp/Gemfile"
    volumes:
      - ./tasks:/myapp
    depends_on:
      - tasks-db
      - broker
    networks:
      - ates


  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - ates

  broker:
    image: confluentinc/cp-kafka:5.4.1
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - ates